#!/usr/bin/env python3
"""Convert base16 schemes (github.com/tinted-theming/schemes, MIT) into greyline
theme TOMLs.

The shipped palettes under worldtime/themes/ are generated by this script — run it
to refresh them, or to add any of the ~340 upstream schemes that greyline doesn't
bundle:

    git clone --depth 1 https://github.com/tinted-theming/schemes /tmp/schemes
    python tools/base16_to_theme.py --curated /tmp/schemes/base16 --out worldtime/themes
    python tools/base16_to_theme.py /tmp/schemes/base16/nord.yaml   # one, to stdout

A greyline theme is a map, not a text editor, so the base16 slots need translating
rather than copying — the mapping below is the whole design, and it was checked
against the hand-tuned 0.6.0 themes it replaces (it reproduces their colours to
within a shade):

    ocean       base00                      the sea / page background
    land        base01, or base02, or the two blended toward base03 — whichever
                first clears `_MIN_CONTRAST` against the ocean on the right side
                (lighter on dark schemes, darker on light): landmasses have to read
                as a distinct surface, and several schemes put base01 within a shade
                or two of base00, or below it
    border      base03                      country outlines
    grid_label  base04                      bottom-edge UTC-offset labels
    dot         base05                      city dots
    text        base06, or base05 where base06 cannot be read against the label
                plate (see `_text_slot`)    clock labels
    logo        base06                      tint for logo_invert
    idl         reddest accent              International Date Line
    gmt         greenest accent             UTC+0 column fill
    home        warmest accent (~amber),    home city dot + label
                or _ACCENT for schemes with a signature accent

Slots are picked by hue, not by base16's nominal "base08 = red" convention, because
schemes disagree: tokyo-night-dark's base08 is lavender and its red lives in base0F.

Polarity comes from the scheme's own `variant` field. The night side MULTIPLIES
toward `night`, so a dark scheme darkens base00 toward black at a low alpha, while a
light scheme needs a mid-tone (base03/base04 blended) and a much stronger alpha to
show a terminator at all. Everything else follows: strokes are halos *behind* text,
so they take the background's polarity, and grid/column tints flip white-on-dark to
black-on-light.
"""

import argparse
import colorsys
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from worldtime.themes import contrast_ratio

CURATED = [
    "gruvbox-dark-hard",
    "gruvbox-dark-medium",
    "gruvbox-dark-soft",
    "gruvbox-light-hard",
    "gruvbox-light-medium",
    "gruvbox-light-soft",
    "everforest-dark-hard",
    "everforest-dark-medium",
    "everforest-dark-soft",
    "everforest-light-hard",
    "everforest-light-medium",
    "everforest-light-soft",
    "rose-pine",
    "rose-pine-moon",
    "rose-pine-dawn",
    "tokyo-night-dark",
    "tokyo-night-storm",
    "tokyo-night-moon",
    "tokyo-night-light",
    "catppuccin-mocha",
    "catppuccin-macchiato",
    "catppuccin-frappe",
    "catppuccin-latte",
    "nord",
    "dracula",
    "solarized-dark",
    "solarized-light",
    "onedark",
    "one-light",
    "kanagawa",
    "monokai",
    "github-dark",
    "github",
]

_OVERRIDE = {
    "tokyo-night-dark": {"home": "base0D"},
    "tokyo-night-storm": {"home": "base0D"},
    "tokyo-night-moon": {"home": "base0D"},
    "tokyo-night-light": {"home": "base0D"},
    "catppuccin-mocha": {"home": "base0E"},
    "catppuccin-macchiato": {"home": "base0E"},
    "catppuccin-frappe": {"home": "base0E"},
    "catppuccin-latte": {"home": "base0E"},
    "monokai": {"idl": "base08"},
    "kanagawa": {"gmt": "base0B"},
}

_ACCENT_SLOTS = [f"base0{c}" for c in "89ABCDEF"]
_SURFACE_SLOTS = ["base01", "base02"]
_MIN_CONTRAST = 18

_ALL_SLOTS = [f"base0{c}" for c in "0123456789ABCDEF"]
_TEXT_MIN_CONTRAST = 4.5  # WCAG 2.2 AA for body-size text
_PLATE_ALPHA = 130  # render.py's default label_bg_alpha

_POLARITY = {
    "dark": {
        "grid": "#ffffff30",
        "column": "#ffffff14",
        "gmt_alpha": 0x34,
        "night_alpha": 12,
        "day_wash_alpha": 0x12,
    },
    "light": {
        "grid": "#00000024",
        "column": "#0000000f",
        "gmt_alpha": 0x3A,
        "night_alpha": 44,
        "day_wash_alpha": 0x10,
    },
}


def parse_scheme(path):
    """Parse a base16 YAML file. These are flat and machine-generated (a dozen
    `key: "value"` lines), so a purpose-built reader beats a PyYAML dependency."""
    meta: dict[str, str] = {}
    palette: dict[str, str] = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = re.match(r'\s*(\w+):\s*"([^"]*)"|\s*(\w+):\s*([^#\n]+)', line)
            if not m:
                continue
            key = m.group(1) or m.group(3)
            value = (m.group(2) if m.group(1) else m.group(4)).strip()
            (palette if key.startswith("base") else meta)[key] = value
    missing = {f"base0{c}" for c in "0123456789ABCDEF"} - set(palette)
    if missing:
        raise ValueError(f"{path}: incomplete palette, missing {sorted(missing)}")
    return meta, {k: v.lower() for k, v in palette.items()}


def _rgb(hex_):
    s = hex_.lstrip("#")
    return tuple(int(s[i : i + 2], 16) for i in (0, 2, 4))


def _hex(rgb):
    r, g, b = (max(0, min(255, round(c))) for c in rgb)
    return f"#{r:02x}{g:02x}{b:02x}"


def _luma(hex_):
    r, g, b = _rgb(hex_)
    return 0.299 * r + 0.587 * g + 0.114 * b


def _scale(hex_, factor):
    return _hex(c * factor for c in _rgb(hex_))


def _mix(a, b):
    return _hex((x + y) / 2 for x, y in zip(_rgb(a), _rgb(b), strict=True))


def _hue_chroma(hex_):
    """Hue in degrees and chroma (max-min channel). Chroma, not HLS saturation:
    a pale pink is ~0.6 "saturated" but carries little colour, and picking it as
    the International Date Line would give a washed-out line."""
    r, g, b = (c / 255 for c in _rgb(hex_))
    h, _, _ = colorsys.rgb_to_hls(r, g, b)
    return h * 360, max(r, g, b) - min(r, g, b)


def _nearest_hue(palette, target, cap, exclude=()):
    """The accent slot that best reads as `target` degrees.

    Hue distance and chroma trade off directly: catppuccin's pale Flamingo sits
    exactly at 0° but carries a sixth of the colour its Red does, so Red takes the
    International Date Line. The `cap` then rules out slots that simply aren't the
    colour asked for however vivid they are (tokyo-night-light's brown is 24° from
    red, its actual red 13°). If nothing clears the cap the scheme has no such
    colour — monokai's "red" is magenta — so the second pass takes the whole ring
    and lets the score decide.

    Washed-out slots are dropped first, relative to how colourful the scheme gets at
    all: catppuccin's Flamingo would otherwise win the date line outright by sitting
    at 0°, and a scheme with no green must not hand back a background tone for the
    UTC+0 column. The floor is relative because muted schemes (nord, everforest) have
    no vivid slot to compare against, and an absolute one would empty them out."""
    chromas = {slot: _hue_chroma(palette[slot])[1] for slot in _ACCENT_SLOTS}
    floor = max(0.08, 0.3 * max(chromas.values()))

    def score(slot):
        hue, chroma = _hue_chroma(palette[slot])
        return abs((hue - target + 180) % 360 - 180) - 80 * chroma

    for max_distance in (cap, 180):
        found = [
            slot
            for slot in _ACCENT_SLOTS
            if slot not in exclude
            and chromas[slot] >= floor
            and abs((_hue_chroma(palette[slot])[0] - target + 180) % 360 - 180) <= max_distance
        ]
        if found:
            return min(found, key=score)
    return _ACCENT_SLOTS[0]


def _land(palette, light):
    """A landmass colour with enough contrast against the ocean to read as coastline.

    base01 is the natural choice and usually clears it, but low-contrast schemes
    (everforest, gruvbox-medium) put it within a few shades of base00, and some
    (tokyo-night, catppuccin) make it *darker* than base00. Falling through to
    base03 would collide with the country borders, so the last resort blends base02
    toward base03 instead — still the scheme's own ramp, just further along it."""
    ocean = _luma(palette["base00"])
    for slot in _SURFACE_SLOTS:
        gap = ocean - _luma(palette[slot]) if light else _luma(palette[slot]) - ocean
        if gap >= _MIN_CONTRAST:
            return palette[slot]
    return _mix(palette["base02"], palette["base03"])


def _over(fg, bg, alpha):
    """`fg` at `alpha` (0-255) composited over `bg`, both hex."""
    t = alpha / 255.0
    return _hex(f * t + b * (1 - t) for f, b in zip(_rgb(fg), _rgb(bg), strict=True))


def _text_slot(palette, light, land):
    """The slot for clock labels: base06, or base05 where base06 cannot be read.

    base06 is the scheme's brightest foreground and is the right answer for 34 of the
    35 bundled schemes. Catppuccin Latte breaks the assumption — its base06 is
    Rosewater, a *light* accent, which lands at 2.02:1 on that theme's light label
    plate, well under AA. base05 is the natural fallback: it is already the colour of
    the city dots, so the theme stays inside its own ramp, and it gives Latte 6.10:1.

    Contrast is measured against the plate render.py actually draws (`label_bg` at
    `_PLATE_ALPHA` over land and over ocean), not the bare map, and the worst of the
    two backdrops wins. The final `max` is a floor, not an expected path: it means no
    generated theme can ship labels that cannot be read, whatever a future scheme does.
    """
    plate = palette["base00"] if light else "#000000"
    backdrops = [_over(plate, bg, _PLATE_ALPHA) for bg in (land, palette["base00"])]

    def worst(slot):
        return min(contrast_ratio(_rgb(palette[slot]), _rgb(b)) for b in backdrops)

    for slot in ("base06", "base05"):
        if worst(slot) >= _TEXT_MIN_CONTRAST:
            return slot
    return max(_ALL_SLOTS, key=worst)


def build_theme(meta, palette, slug):
    """Return the theme as (key, value, comment) rows, in file order."""
    light = meta.get("variant", "dark").lower() == "light"
    p = _POLARITY["light" if light else "dark"]

    land = _land(palette, light)
    text = _text_slot(palette, light, land)
    over = _OVERRIDE.get(slug, {})
    idl = over.get("idl") or _nearest_hue(palette, 0, cap=20)
    gmt = over.get("gmt") or _nearest_hue(palette, 120, cap=80, exclude={idl})
    home = over.get("home") or _nearest_hue(palette, 45, cap=60, exclude={idl, gmt})

    if light:
        stroke = palette["base00"]
        night = _mix(palette["base03"], palette["base04"])
        day_wash = palette["base00"]
    else:
        stroke = _scale(palette["base00"], 0.45)
        night = _scale(palette["base00"], 0.4)
        day_wash = palette["base05"]

    return [
        ("# Map surfaces", None, None),
        ("ocean", palette["base00"], "base00"),
        ("land", land, "landmasses"),
        ("border", palette["base03"], "base03"),
        ("grid", p["grid"], "timezone boundary lines"),
        ("grid_label", palette["base04"], "base04"),
        ("gmt", palette[gmt] + f"{p['gmt_alpha']:02x}", f"{gmt}, green UTC+0 column"),
        ("idl", palette[idl], f"{idl}, red International Date Line"),
        ("column", p["column"], "home timezone-column highlight"),
        ("", None, None),
        ("# Day/night overlay", None, None),
        ("night", night, "base03+base04" if light else "base00, darkened"),
        ("day_wash", day_wash + f"{p['day_wash_alpha']:02x}", "base00" if light else "base05"),
        ("night_alpha", p["night_alpha"], None),
        ("", None, None),
        ("# Clocks", None, None),
        (
            "text",
            palette[text],
            text if text == "base06" else f"{text} — base06 fails contrast on the plate",
        ),
        ("text_stroke", stroke + "dc", None),
        ("dot", palette["base05"], "base05"),
        ("dot_outline", stroke + "d2", None),
        ("home", palette[home], f"{home}, the accent"),
        ("home_stroke", stroke + "dc", None),
        ("", None, None),
        ("# Optional extras", None, None),
        ("logo", palette["base06"], "tint for logo_invert"),
    ] + (
        [("label_bg", palette["base00"], "plate behind labels; dark text needs a light one")]
        if light
        else []
    )


def to_toml(meta, palette, slug):
    name = meta.get("name", slug)
    author = meta.get("author", "")
    lines = [
        f"# {name} — generated from the base16 scheme {slug!r}",
        f"# (https://github.com/tinted-theming/schemes, MIT). Author: {author}.",
        "# Regenerate with tools/base16_to_theme.py; edit that, not this file.",
        f'name = "{name}"',
        "",
    ]
    for key, value, comment in build_theme(meta, palette, slug):
        if value is None:
            lines.append(key)
            continue
        rendered = value if isinstance(value, int) else f'"{value}"'
        entry = f"{key} = {rendered}"
        lines.append(f"{entry:<27}# {comment}" if comment else entry)
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument(
        "source",
        help="a base16 .yaml file, or the schemes/base16 directory when --curated is given",
    )
    ap.add_argument(
        "--curated", action="store_true", help="regenerate every scheme greyline bundles"
    )
    ap.add_argument("--out", help="directory to write into (default: stdout)")
    args = ap.parse_args(argv)

    if not args.curated:
        meta, palette = parse_scheme(args.source)
        slug = meta.get("slug") or os.path.basename(args.source).removesuffix(".yaml")
        toml = to_toml(meta, palette, slug)
        if not args.out:
            sys.stdout.write(toml)
            return 0
        with open(os.path.join(args.out, f"{slug}.toml"), "w", encoding="utf-8") as f:
            f.write(toml)
        return 0

    if not args.out:
        ap.error("--curated needs --out")
    for slug in CURATED:
        path = os.path.join(args.source, f"{slug}.yaml")
        meta, palette = parse_scheme(path)
        with open(os.path.join(args.out, f"{slug}.toml"), "w", encoding="utf-8") as f:
            f.write(to_toml(meta, palette, slug))
        print(f"wrote {slug}.toml", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
